#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path
import re
DATA={
'services/products/lv-mv-switchgear.html':{'old':'../../assets/images/real/electrical-switchgear.jpeg','new':'../../assets/images/products/generated/lv-mv-switchgear-realistic.jpg','alt':'تابلو برق صنعتی LV و MV Switchgear با سلول‌های حفاظتی و کنترل','mark':'switchgear-deep-2026','section':'''<section class="ptf-box" data-deep-upgrade="switchgear-deep-2026"><h2>راهنمای عمیق انتخاب Switchgear برای بهره‌بردار، برق و ایمنی</h2><p>در تابلو LV/MV، خرید فقط انتخاب یک تابلو با جریان نامی مشخص نیست. سطح اتصال کوتاه، Icw، Ipk، فرم جداسازی، تهویه، IP، نوع کلید، حفاظت و قابلیت تعمیرات تعیین می‌کند تابلو در خطای واقعی چه رفتاری دارد. برای کاربر بهره‌بردار، دسترسی ایمن به فیدر، امکان جداسازی، قفل‌های مکانیکی و الکتریکی و وضوح سیگنال‌ها به اندازه برند کلید اهمیت دارد.</p><p>در MV Switchgear، نوع AIS یا GIS، Fixed یا Withdrawable بودن VCB، رله حفاظتی، CT/PT و Arc Flash Protection باید با فلسفه بهره‌برداری هماهنگ باشد. در LV، Form 2/3/4، نوع ACB/MCCB، Selectivity و ظرفیت باسبار روی ایمنی و پایداری شبکه اثر مستقیم دارد. اگر سطح اتصال کوتاه واقعی شبکه یا Expansion آینده دیده نشود، تابلو ممکن است در چند سال اول نیازمند تغییرات پرهزینه شود.</p><p>برای برندهایی مانند Siemens، Schneider Electric، ABB، Eaton، LS Electric و Rittal باید فقط نام برند دیده نشود؛ سری محصول، Breaking Capacity، Type Test، Routine Test، امکان تأمین Spare Part، سازگاری با رله‌ها و مدارک FAT باید مقایسه شود. در پروژه‌های حساس، SLD، Load List، Protection Study و نقشه‌های Wiring باید قبل از ساخت نهایی Freeze شوند.</p></section>'''},
'services/products/vfd-soft-starter.html':{'old':'../../assets/images/real/closeup-electrical-panel.jpg','new':'../../assets/images/products/generated/vfd-soft-starter-realistic.jpg','alt':'درایو فرکانس متغیر VFD و سافت استارتر صنعتی برای کنترل موتور','mark':'vfd-deep-2026','section':'''<section class="ptf-box" data-deep-upgrade="vfd-deep-2026"><h2>راهنمای عمیق انتخاب VFD و Soft Starter بر اساس بار واقعی موتور</h2><p>VFD و Soft Starter هر دو جریان راه‌اندازی را مدیریت می‌کنند، اما هدف یکسانی ندارند. Soft Starter برای راه‌اندازی و توقف نرم مناسب است، ولی کنترل سرعت پیوسته نمی‌دهد. VFD زمانی ارزش دارد که بار متغیر باشد، مثل پمپ و فن، و کاهش سرعت بتواند مصرف انرژی را کم کند. بنابراین قبل از خرید باید مشخص شود هدف کاهش تنش راه‌اندازی است یا کنترل فرایندی و صرفه‌جویی انرژی.</p><p>برای VFD، نوع بار اهمیت دارد: بار گشتاور متغیر مثل فن و پمپ با بار گشتاور ثابت مثل کانوایر یا اکسترودر متفاوت است. Overload، دمای محیط، ارتفاع نصب، تهویه تابلو، طول کابل موتور، نیاز به dv/dt یا Sine Filter و هارمونیک شبکه باید بررسی شود. در توان‌های بالا، نادیده گرفتن IEEE 519 یا الزامات هارمونیک می‌تواند کیفیت برق سایت را تحت تأثیر قرار دهد.</p><p>در مقایسه برندهایی مثل Siemens، Schneider Electric، ABB، Danfoss، LS Electric یا Omron باید فقط kW و قیمت مقایسه نشود. قابلیت PID، ارتباط Modbus/Profibus/Profinet، EMC Filter، Bypass، Serviceability، نرم‌افزار تنظیمات و موجودی قطعات روی بهره‌برداری واقعی اثر دارد. برای موتورهای قدیمی، سازگاری عایق با PWM و ریسک Bearing Current نیز باید بررسی شود.</p></section>'''},
'services/products/industrial-circuit-breakers.html':{'old':'../../assets/images/real/electrical-switchgear.jpeg','new':'../../assets/images/products/generated/industrial-circuit-breakers-realistic.jpg','alt':'کلیدهای صنعتی ACB MCCB و VCB برای حفاظت تابلوهای برق','mark':'breakers-deep-2026','section':'''<section class="ptf-box" data-deep-upgrade="breakers-deep-2026"><h2>راهنمای عمیق انتخاب ACB، MCCB و VCB بر اساس حفاظت واقعی شبکه</h2><p>کلید صنعتی فقط یک وسیله قطع و وصل نیست؛ نقطه تصمیم‌گیری حفاظتی شبکه است. اگر Breaking Capacity کمتر از سطح خطای واقعی باشد، کلید در خطا ایمن عمل نمی‌کند. اگر تنظیمات Trip Unit با شبکه هماهنگ نباشد، یا بی‌دلیل فیدر اصلی قطع می‌شود یا خطای پایین‌دست دیر پاک می‌شود. بنابراین انتخاب ACB، MCCB یا VCB باید همراه با Short Circuit Study و Coordination انجام شود.</p><p>در LV، Icu و Ics باید جداگانه دیده شوند. Icu ظرفیت قطع نهایی است، اما Ics نشان می‌دهد کلید پس از قطع خطا تا چه سطحی قابل بهره‌برداری سرویس است. برای فیدرهای حیاتی، Electronic Trip Unit با LSIG و قابلیت تنظیم دقیق می‌تواند Selectivity را بهتر کند. در MV، VCB باید با رله حفاظتی، CT، مکانیزم شارژ، Interlock و تست‌های مکانیکی هماهنگ باشد.</p><p>در مقایسه برندهایی مثل Schneider Electric، Siemens، ABB، Eaton، LS Electric و Legrand باید به سری محصول، منحنی حفاظتی، Accessoryها، ابعاد نصب، امکان Draw-out، تست‌ها و موجودی Spare Part توجه شود. در پروژه Retrofit، ابعاد فیزیکی و سازگاری Busbar گاهی از مشخصات اسمی مهم‌تر است.</p></section>'''},
'services/products/power-transformer.html':{'old':'../../assets/images/real/real-transmission-substation.jpg','new':'../../assets/images/products/generated/power-transformer-realistic.jpg','alt':'ترانسفورماتور توزیع روغنی با رادیاتور و بوشینگ برای پست صنعتی','mark':'transformer-deep-2026','section':'''<section class="ptf-box" data-deep-upgrade="transformer-deep-2026"><h2>راهنمای عمیق انتخاب ترانسفورماتور بر اساس بار، تلفات و بهره‌برداری</h2><p>در ترانسفورماتور، قیمت خرید اولیه فقط بخشی از هزینه واقعی است. تلفات بی‌باری و بارداری در طول عمر تجهیز می‌تواند از اختلاف قیمت اولیه چند پیشنهاد بیشتر شود. برای بهره‌بردار، راندمان، دمای کاری، سطح صدا، امکان سرویس، کیفیت روغن و دسترسی به Tap Changer اهمیت عملیاتی دارد. بنابراین در RFQ باید علاوه بر kVA/MVA، تلفات تضمینی و روش تست هم ذکر شود.</p><p>Vector Group، درصد امپدانس، نوع خنک‌کاری و Tap Range باید با شبکه سایت هماهنگ باشد. امپدانس روی سطح اتصال کوتاه پایین‌دست و افت ولتاژ اثر دارد. Vector Group روی موازی‌کردن ترانس‌ها و سازگاری با شبکه مهم است. در محیط‌های داخلی یا حساس، Dry Type Cast Resin ممکن است از نظر ایمنی آتش و نگهداری مناسب‌تر باشد، اما محدودیت حرارتی و هزینه خود را دارد.</p><p>در مقایسه سازندگان، باید Routine Test، Type Test، Temperature Rise، Oil Test، Partial Discharge در صورت نیاز، کیفیت Core و Winding و امکانات حفاظتی مثل Buchholz، OTI، WTI و Pressure Relief Device بررسی شود. برند یا سازنده معتبر بدون گزارش تست کامل برای پروژه صنعتی کافی نیست.</p></section>'''}
}
for fp,d in DATA.items():
 p=Path(fp); s=p.read_text(encoding='utf-8',errors='ignore')
 if d['mark'] in s: continue
 old_abs='https://pishtaj.ir/'+d['old'].replace('../../',''); new_abs='https://pishtaj.ir/'+d['new'].replace('../../','')
 s=s.replace(d['old'],d['new']).replace(old_abs,new_abs)
 s=re.sub(r'(<div class="ptf-hero-card"><img src="'+re.escape(d['new'])+r'" alt=")[^"]*(" width=")',r'\1'+d['alt']+r'\2',s,count=1)
 idx=s.find('<div class="ptf-cta">')
 if idx!=-1: s=s[:idx]+d['section']+s[idx:]
 p.write_text(s,encoding='utf-8')
print('upgraded',len(DATA))
