#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path
import re

REMOVE = [
'در تحویل پروژه، کنترل بسته‌بندی، پلاک، Marking، گواهی‌ها، دستورالعمل نصب و مدارک تست ضروری است. اگر این موارد از ابتدا در RFQ نیاید، اختلاف‌ها معمولاً در نصب یا راه‌اندازی ظاهر می‌شوند و هزینه بیشتری ایجاد می‌کنند.'
]
def visible(s): return re.sub(r'\s+',' ', re.sub(r'<[^>]+>',' ',s)).strip()
def clean(html):
    def repl(m): return '' if visible(m.group(1)) in REMOVE else m.group(0)
    return re.sub(r'<p\b[^>]*>([\s\S]*?)</p>', repl, html)
EXTRAS={
'services/products/thermowell.html': '''<section class="ptf-box" data-product-depth-phase3-final="thermowell"><h2>تکمیل طراحی و کنترل ترموول در خرید پروژه‌ای</h2><p>در پروژه‌های بزرگ، ترموول‌ها معمولاً در تعداد زیاد و با طول‌ها و متریال‌های نزدیک خریداری می‌شوند. برای جلوگیری از اشتباه، بهتر است schedule ترموول شامل tag، line number، service، material، insertion length، process connection، lagging extension، bore و نوع سنسور تهیه شود. اگر چند ترموول مشابه اما با طول متفاوت در یک بسته ارسال شوند، نبود tag و marking مناسب در انبار باعث نصب اشتباه خواهد شد. نصب ترموول کوتاه‌تر در خط بزرگ ممکن است دمای نزدیک دیواره را نشان دهد و کنترل فرایند را گمراه کند.</p><p>در سرویس‌های erosive یا slurry، علاوه بر محاسبه ارتعاش، سایش نوک ترموول و متریال مقاوم باید بررسی شود. در سرویس‌های بسیار خورنده، استفاده از پوشش یا alloy خاص باید با زمان تحویل و قابلیت ساخت مقایسه شود. اگر سنسور باید بدون توقف فرایند تعویض شود، طراحی ترموول و دسترسی به head اهمیت بیشتری پیدا می‌کند. برای سیستم‌های safety، proof test و دوره کالیبراسیون سنسور نیز باید در مدارک بهره‌برداری ثبت شود.</p><p>در زمان FAT یا بازرسی قبل از حمل، کنترل ابعادی، تست متریال، کیفیت سطح، thread gauge در اتصالات رزوه‌ای و وضعیت flange face انجام می‌شود. برای ترموول‌های جوشی، WPS/PQR و NDT در صورت الزام پروژه باید پیش از حمل آماده باشد. این کنترل‌ها باعث می‌شود قطعه‌ای که از نظر ظاهری ساده است، در سایت به نقطه ضعف مکانیکی یا ابزاردقیق تبدیل نشود.</p></section>''',
'services/products/fire-tube-boiler.html': '''<section class="ptf-box" data-product-depth-phase3-final="firetube"><h2>تکمیل محدوده تامین بویلر و پکیج‌های جانبی</h2><p>در خرید بویلر فایرتیوب باید محدوده تامین دقیق مشخص شود. گاهی پیشنهاد فقط شامل بدنه بویلر و burner است، اما پروژه به feedwater pump، deaerator، chemical dosing، blowdown tank، sample cooler، economizer، stack، control panel، gas train، safety valve و platform هم نیاز دارد. اگر این مرزها در RFQ روشن نباشد، مقایسه قیمت‌ها گمراه‌کننده خواهد بود. یک پیشنهاد ارزان‌تر ممکن است بخش زیادی از اقلام ضروری راه‌اندازی را خارج از scope گذاشته باشد.</p><p>کیفیت آب تغذیه یکی از مهم‌ترین عوامل عمر بویلر است. سختی، اکسیژن، TDS، pH، silica و مواد شیمیایی باید با دستور سازنده و استاندارد بهره‌برداری هماهنگ شوند. اگر سیستم water treatment یا deaerator ضعیف باشد، رسوب و خوردگی خیلی زود راندمان را کاهش می‌دهد. برنامه blowdown نیز باید بر اساس کیفیت آب و بار بویلر تنظیم شود. blowdown زیاد اتلاف انرژی ایجاد می‌کند و blowdown کم باعث افزایش TDS و رسوب می‌شود.</p><p>در تحویل و راه‌اندازی، تست‌های ایمنی باید مستند شوند: low water cutoff، high pressure trip، flame failure، purge sequence، fuel valve tightness، safety valve و emergency stop. اپراتور باید آموزش ببیند که چه شرایطی نیاز به shutdown فوری دارد. Data Book نهایی باید شامل نقشه‌ها، مدارک فشار، تست‌ها، تنظیمات burner، دستورالعمل بهره‌برداری و برنامه نگهداری باشد تا بویلر فقط نصب نشود، بلکه ایمن و پایدار بهره‌برداری شود.</p></section>''',
'services/products/hazardous-area-cctv-access-control.html': '''<section class="ptf-box" data-product-depth-phase3-final="hazcctv"><h2>جزئیات تکمیلی برای طراحی و تحویل CCTV صنعتی</h2><p>در محیط‌های فرایندی، هدف هر دوربین باید از ابتدا تعریف شود. دوربینی که برای مشاهده وضعیت شعله، سطح مخزن یا مسیر تردد نصب می‌شود با دوربینی که برای شناسایی چهره یا پلاک لازم است تفاوت دارد. معیارهایی مانند pixels per meter، field of view، lens، frame rate، low-light performance و محل نصب باید بر اساس هدف انتخاب شوند. اگر هدف مشخص نباشد، ممکن است تعداد زیادی دوربین نصب شود اما تصویر مورد نیاز در حادثه یا audit قابل استفاده نباشد.</p><p>برای شبکه و ذخیره‌سازی، محاسبه پهنای باند و ظرفیت storage ضروری است. تغییر resolution یا frame rate پس از نصب می‌تواند retention time را کاهش دهد. اگر سایت نیاز به نگهداری تصویر برای ۳۰ یا ۹۰ روز دارد، باید bitrate واقعی، فشرده‌سازی، motion recording و redundancy storage بررسی شود. در سایت‌های حساس، دسترسی کاربران به تصاویر، audit log و سیاست password نیز بخشی از امنیت سیستم است.</p><p>در تحویل سیستم، باید نقشه IP، نام کاربری‌های تحویلی، محل دوربین‌ها، certificateهای Ex، تنظیمات VMS، backup configuration و برنامه نگهداری ارائه شود. برای access control، تست قطع برق، خروج اضطراری، ارتباط با fire alarm و ثبت رخدادها باید انجام شود. اگر تجهیز در hazardous area نصب است، هر بازدید دوره‌ای باید وضعیت cable gland، درپوش‌ها، gasket و خوردگی housing را نیز کنترل کند.</p></section>''',
'services/products/chemical-injection-package.html': '''<section class="ptf-box" data-product-depth-phase3-final="chemical"><h2>تکمیل طراحی ایمنی و بهره‌برداری پکیج تزریق</h2><p>پکیج تزریق مواد شیمیایی باید با ایمنی اپراتور هماهنگ باشد. شارژ مخزن، بازکردن line، تعویض diaphragm یا رفع گرفتگی injection quill می‌تواند تماس با مواد خطرناک ایجاد کند. بنابراین محل drain، سینی جمع‌آوری، bund، ventilation، eyewash، PPE، برچسب‌گذاری و روش تخلیه باید در طراحی دیده شود. اگر ماده قابل اشتعال یا سمی است، تجهیزات الکتریکی و ابزار دقیق باید با area classification و MSDS هماهنگ شوند.</p><p>در بهره‌برداری، دبی پمپ metering ممکن است با تغییر back pressure، گرفتگی check valve، هواگرفتگی مکش یا تغییر ویسکوزیته تغییر کند. به همین دلیل calibration pot و برنامه verification دوره‌ای ضروری است. برای مواد پلیمر یا مواد چسبنده، سرعت مکش، قطر tubing و زمان ماند در خط باید بررسی شود. برای مواد crystallizing، flushing و heat tracing ممکن است لازم باشد. انتخاب pump head و valve material بدون درک رفتار ماده در دمای سایت، ریسک خرابی را بالا می‌برد.</p><p>در Data Book باید P&ID، لیست valveها، متریال wetted parts، datasheet پمپ، منحنی یا جدول ظرفیت، manual، تست نشتی، تنظیمات کنترل و spare list وجود داشته باشد. اگر پکیج چند پمپ duty/standby دارد، logic تغییر مسیر و تست دوره‌ای پمپ standby باید مشخص شود. این مدارک به بهره‌بردار کمک می‌کند تزریق شیمیایی را پایدار و قابل ردیابی نگه دارد.</p></section>''',
'services/products/pipe-supports-spring-hangers.html': '''<section class="ptf-box" data-product-depth-phase3-final="pipe-support"><h2>ساپورت پایپینگ و Spring Hanger؛ کنترل بار، حرکت و نصب</h2><p>ساپورت پایپینگ فقط یک قطعه فلزی برای نگه داشتن لوله نیست؛ بخشی از تحلیل تنش، کنترل ارتعاش، مدیریت انبساط حرارتی و حفاظت تجهیزات متصل به پایپینگ است. در خطوط بخار، دمای بالا، خطوط رفت و برگشت، پایپینگ پمپ و تجهیزات حساس، انتخاب اشتباه ساپورت می‌تواند باعث بار اضافی روی nozzle، شکم‌دادگی خط، گیرکردن حرکت حرارتی یا vibration شود. Spring hanger زمانی لازم می‌شود که لوله در اثر تغییر دما حرکت عمودی دارد و ساپورت rigid نمی‌تواند آن حرکت را بدون ایجاد بار اضافی تحمل کند.</p><p>در RFQ باید نوع ساپورت، load، travel، cold/hot setting، جهت حرکت، line number، insulation، shoe requirement، material، coating، استاندارد ساخت، drawing و موقعیت نصب مشخص شود. برای spring support، load variation، spring rate، travel range، preset، lock pin و nameplate اهمیت دارد. اگر load واقعی با اطلاعات طراحی متفاوت باشد، spring در موقعیت درست کار نمی‌کند و خط در حالت hot بار نامناسب به سازه یا تجهیز وارد می‌کند.</p><h2>تست، تحویل و نصب</h2><p>برای spring hanger، test report و calibration/load test اهمیت دارد. در تحویل باید tag، cold load، hot load، travel، direction، lock pin و painting کنترل شود. در نصب، lock pin نباید پیش از زمان مناسب آزاد شود و موقعیت cold setting باید با drawing مطابقت داشته باشد. برای ساپورت‌های ثابت، guide، anchor، slide plate و shoe باید با حرکت حرارتی خط هماهنگ باشد. اگر PTFE slide plate آسیب ببیند یا در نصب جوشکاری اشتباه انجام شود، اصطکاک افزایش می‌یابد و تحلیل تنش واقعی تغییر می‌کند.</p><table><tr><th>نوع ساپورت</th><th>داده لازم</th><th>ریسک انتخاب ناقص</th></tr><tr><td>Rigid Support</td><td>Load، elevation، shoe، insulation</td><td>نشست خط یا بار اضافی</td></tr><tr><td>Spring Hanger</td><td>Cold/hot load، travel، spring rate</td><td>گیرکردن حرکت یا overload</td></tr><tr><td>Guide/Anchor</td><td>جهت حرکت، load، اصطکاک، سازه</td><td>تغییر مسیر انبساط یا stress بالا</td></tr><tr><td>Slide Plate</td><td>Material، temperature، surface، friction</td><td>حرکت نامطلوب و بار روی nozzle</td></tr></table><p>برای پذیرش، بهتر است ساپورت‌ها بر اساس line number و isometric بسته‌بندی شوند. گم شدن یک spring hanger یا نصب آن در موقعیت اشتباه می‌تواند راه‌اندازی خط را به تأخیر بیندازد. Data Book باید شامل drawing، load table، test report، coating و دستور نصب باشد.</p></section>'''
}

for rel, extra in EXTRAS.items():
    p=Path(rel)
    html=clean(p.read_text(encoding='utf-8'))
    marker=extra.split('data-product-depth-phase3-final="',1)[1].split('"',1)[0]
    if f'data-product-depth-phase3-final="{marker}"' not in html:
        html=html.replace('</article>', extra+'</article>', 1)
    p.write_text(html, encoding='utf-8')
    print('extended', rel)
