#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path
import re

DUP_TEXTS=[
'در ارزیابی نهایی، پیشنهادها باید با جدول TBE مقایسه شوند. استاندارد، متریال، برند، مدارک، زمان تحویل، انحراف‌های فنی، اقلام جانبی و خدمات پس از فروش باید هم‌زمان دیده شوند. فقط پس از هم‌سطح‌سازی فنی است که مقایسه قیمت معنا پیدا می‌کند.',
'در تحویل پروژه، کنترل بسته‌بندی، پلاک، Marking، گواهی‌ها، دستورالعمل نصب و مدارک تست ضروری است. اگر این موارد از ابتدا در RFQ نیاید، اختلاف‌ها معمولاً در نصب یا راه‌اندازی ظاهر می‌شوند.'
]
def visible(s): return re.sub(r'\s+',' ', re.sub(r'<[^>]+>',' ',s)).strip()
def remove_dup(html):
    def repl(m): return '' if visible(m.group(1)) in DUP_TEXTS else m.group(0)
    return re.sub(r'<p\b[^>]*>([\s\S]*?)</p>', repl, html)

EXTRAS={
'brands/abb-industrial.html': '''<section class="box" data-mixed-phase2-depth="abb"><h2>تکمیل ارزیابی ABB در پروژه‌های EPC و تعمیرات</h2><p>در پروژه‌های EPC، تجهیزات ABB معمولاً بخشی از یک سیستم بزرگ‌تر هستند؛ برای مثال breaker در تابلو LV، relay در protection panel، drive در MCC، یا motor در پکیج مکانیکی. بنابراین هر خرید باید با interfaceهای اطراف خود بررسی شود. اگر breaker جدید با door interlock، busbar adaptor یا communication module تابلو هماهنگ نباشد، حتی با rating درست نیز نصب متوقف می‌شود. اگر drive با PLC موجود پروتکل مشترک نداشته باشد، تیم کنترل مجبور به تغییر logic یا افزودن gateway می‌شود. این هزینه‌ها معمولاً در قیمت اولیه دیده نمی‌شوند.</p><p>در تعمیرات اضطراری، بهتر است عکس پلاک، wiring، option card، firmware و محل نصب تجهیز معیوب همراه RFQ ارسال شود. در بعضی خانواده‌های ABB، یک حرف یا عدد در type code می‌تواند به تفاوت در frame، ولتاژ، braking، EMC، enclosure یا communication منجر شود. برای همین، فروشنده باید دقیقاً همان کد یا جایگزین مستند ارائه کند و تفاوت‌ها را در جدول deviation بنویسد. اگر تجهیز discontinued شده، جایگزین باید از نظر ابعاد، accessory، terminal layout و نرم‌افزار بررسی شود.</p><h2>FAT و پذیرش برای تجهیزات ABB</h2><p>در FAT تابلو یا پکیج‌های دارای ABB، تست عملکرد حفاظتی، trip، reset، communication، local/remote command، alarm و interlock باید روی drawing واقعی انجام شود. برای driveها، بهتر است پارامترهای اولیه، motor data، جهت چرخش، ramp، protection و fault history template ثبت شود. برای relayها، setting file و نسخه firmware باید در Data Book قرار گیرد. این مستندات در راه‌اندازی و عیب‌یابی بعدی ارزش عملی دارند.</p><ul><li>برای breaker، accessoryهای نصب و فرمان باید جداگانه در BOM کنترل شوند.</li><li>برای drive، فیلتر EMC و تهویه تابلو نباید بعد از خرید تصمیم‌گیری شود.</li><li>برای motor، orientation جعبه ترمینال و روش نصب روی base باید مشخص باشد.</li><li>برای relay، CT/VT ratio و logic trip باید با protection study همخوان باشد.</li></ul><p>در انبار پروژه، تجهیزات الکترونیکی ABB باید در شرایط مناسب نگهداری شوند. رطوبت، گردوغبار، تخلیه الکترواستاتیک و ضربه می‌تواند کارت‌ها و درایوها را قبل از نصب آسیب‌پذیر کند. بنابراین کنترل بسته‌بندی و شرایط نگهداری بخشی از کیفیت خرید است.</p></section>''',
'brands/yokogawa-industrial.html': '''<section class="box" data-mixed-phase2-depth="yokogawa"><h2>تکمیل ارزیابی Yokogawa در پروژه‌های کنترل فرایند</h2><p>در سیستم‌های کنترل فرایند، تجهیزات Yokogawa معمولاً با معماری موجود سایت ارتباط مستقیم دارند. اگر یک کارت I/O، power module یا communication module برای DCS خریداری می‌شود، باید نسخه سیستم، redundancy، cabinet layout، spare philosophy و شرایط shutdown بررسی شود. قطعه‌ای که از نظر part number نزدیک است اما با revision نرم‌افزاری یا rack موجود سازگار نیست، در لحظه تعویض مشکل ایجاد می‌کند. برای همین، RFQ قطعات DCS باید علاوه بر part number، اطلاعات سیستم موجود و عکس label تجهیز نصب‌شده را هم داشته باشد.</p><p>در ابزار دقیق field، pre-configuration می‌تواند زمان commissioning را کاهش دهد. برای هر tag باید range، unit، damping، output، alarm direction، protocol و tag plate مشخص باشد. اگر تنظیمات در کارخانه یا قبل از ارسال انجام می‌شود، فایل schedule باید به تایید تیم ابزار دقیق برسد. در غیر این صورت، تیم راه‌اندازی مجبور می‌شود تعداد زیادی تجهیز را در سایت تنظیم کند و احتمال خطای انسانی بالا می‌رود.</p><h2>آنالایزرها و سیستم نمونه‌برداری</h2><p>در آنالایزرهای فرایندی، بخش sample conditioning اغلب تعیین‌کننده‌تر از خود analyzer است. فشار و دمای نمونه، رطوبت، ذرات، condensate، زمان تأخیر، مواد سازگار، drain و calibration gas باید بررسی شوند. اگر نمونه به‌درستی آماده نشود، analyzer ممکن است drift کند یا maintenance زیاد بخواهد. برای pH و conductivity، محل نصب سنسور، جریان نمونه، رسوب و برنامه کالیبراسیون اهمیت دارد. برای oxygen analyzer، دمای probe و شرایط احتراق یا دودکش باید کنترل شود.</p><p>مدارک analyzer باید شامل datasheet، P&ID نمونه‌برداری، utility requirement، calibration procedure، spare consumable list و manual باشد. برای تجهیزات Ex، certificate و نصب cable gland باید با area classification هماهنگ باشد. اگر analyzer برای گزارش محیط‌زیست یا کنترل کیفیت محصول استفاده می‌شود، traceability و روش نگهداری داده‌ها نیز مهم است.</p><h2>نگهداری و مدیریت lifecycle</h2><p>در installed baseهای Yokogawa، بهتر است لیست قطعات نصب‌شده شامل tag، model، serial، firmware، محل نصب، نسخه نرم‌افزار و spareهای حیاتی تهیه شود. این داده‌ها در زمان shutdown، migration یا خرابی اضطراری بسیار ارزشمند هستند. اگر قطعه‌ای دیگر تولید نمی‌شود، جایگزین باید نه فقط از نظر عملکرد، بلکه از نظر wiring، configuration، firmware و مدارک با سیستم موجود سازگار باشد.</p><ul><li>برای transmitterها، configuration نهایی در Data Book ذخیره شود.</li><li>برای DCS spare، سازگاری با cabinet و system version کنترل شود.</li><li>برای recorderها، فرمت export و الزامات ثبت داده بررسی شود.</li><li>برای analyzerها، مواد مصرفی و برنامه کالیبراسیون همراه خرید دیده شود.</li></ul><p>این سطح از مستندسازی باعث می‌شود خرید Yokogawa از یک تامین موردی به مدیریت چرخه عمر تجهیزات کنترل فرایند تبدیل شود و ریسک توقف ناگهانی کاهش یابد.</p></section>''',
'brands/grundfos-pumps.html': '''<section class="box" data-mixed-phase2-depth="grundfos"><h2>تکمیل ارزیابی فنی Grundfos در بهره‌برداری واقعی</h2><p>در انتخاب پمپ Grundfos، بهترین نقطه کاری یا BEP باید با duty point پروژه مقایسه شود. اگر پمپ همیشه دور از BEP کار کند، لرزش، مصرف انرژی، خرابی seal و صدای غیرعادی افزایش می‌یابد. برای سیستم‌هایی که مصرف متغیر دارند، VFD و کنترل فشار می‌تواند مفید باشد، اما فقط زمانی که minimum flow، cooling موتور و فشار مورد نیاز مصرف‌کننده‌ها درست تعریف شده باشد. در بوسترها، اگر pressure setpoint بیش از حد بالا انتخاب شود، نشتی شبکه و مصرف انرژی افزایش می‌یابد.</p><p>در پمپ‌های RO یا آب تصفیه‌شده، متریال و کیفیت آب اهمیت زیادی دارد. کلراید، pH، دما، مواد شیمیایی شست‌وشو و ذرات می‌توانند روی stainless grade، seal و عمر پمپ اثر بگذارند. برای dosing pump، انتخاب متریال بدون دیتاشیت ماده شیمیایی خطرناک است. برخی مواد باعث تورم diaphragm، خوردگی head یا گرفتگی valve می‌شوند. بنابراین MSDS یا حداقل نام دقیق ماده، غلظت، دما و ویسکوزیته باید همراه RFQ ارسال شود.</p><h2>نصب، NPSH و عیب‌یابی</h2><p>بسیاری از مشکلات پمپ در نصب ریشه دارد. لوله مکش کوچک، زانویی نزدیک نازل، هواگرفتگی، strainer کثیف، نصب بدون تراز یا وزن پایپینگ روی نازل باعث کاویتاسیون و لرزش می‌شود. برای پمپ‌های vertical multistage، هم‌راستایی، base، جهت چرخش و venting باید کنترل شود. اگر پمپ بعد از راه‌اندازی آمپر بالا می‌کشد، باید duty point واقعی، جهت چرخش، گرفتگی مسیر و تنظیم VFD بررسی شود.</p><p>برای تحویل، curve واقعی، motor plate، seal code، serial، accessoryها، manual و warranty باید ثبت شود. اگر پمپ به صورت پکیج booster تحویل می‌شود، کنترلر، pressure transmitter، bladder tank، valveها، panel و wiring نیز باید با سفارش مطابقت داشته باشد. Data Book پمپ باید فقط شامل بروشور عمومی نباشد؛ duty point، curve، spare list و تنظیمات کنترل باید در آن باشد.</p><h2>قطعات یدکی و هزینه چرخه عمر</h2><p>در پمپ‌های Grundfos، قطعات یدکی مانند mechanical seal، O-ring، bearing، impeller stack، coupling، sensor و kitهای dosing باید با مدل و serial دقیق تطبیق داده شوند. استفاده از seal نامتناسب ممکن است در ابتدا نصب شود اما در دما، فشار یا ماده شیمیایی واقعی دوام نیاورد. برای پمپ‌های critical، بهتر است spare بر اساس MTBF، زمان تامین، نقش پمپ در تولید و امکان standby تعریف شود.</p><ul><li>برای booster، تعداد start/stop و pressure fluctuation پایش شود.</li><li>برای dosing، calibration pot و back pressure valve در طراحی دیده شود.</li><li>برای RO، کیفیت آب و cleaning chemical با متریال پمپ مقایسه شود.</li><li>برای پمپ‌های VFD، minimum speed و cooling موتور بررسی شود.</li></ul><p>در ارزیابی اقتصادی، قیمت خرید فقط بخشی از تصمیم است. انرژی، سرویس، خرابی، قطعات یدکی و زمان توقف باید در total cost of ownership دیده شود. این رویکرد باعث می‌شود پیشنهاد ارزان ولی پرمصرف یا پرریسک، به‌اشتباه انتخاب نشود.</p></section>''',
'services/products/ultrasonic-flowmeter.html': '''<section class="ptf-box" data-mixed-phase2-depth="ultrasonic"><h2>تکمیل معیارهای نصب و پذیرش فلومتر التراسونیک</h2><p>در فلومترهای clamp-on، کیفیت نصب transducer مهم‌ترین عامل موفقیت است. فاصله دو سنسور باید بر اساس جنس لوله، ضخامت، قطر داخلی، نوع سیال و روش V/Z/W محاسبه شود. اگر سطح لوله رنگ ضخیم، زنگ‌زدگی یا عایق داشته باشد، باید آماده‌سازی سطح انجام شود. استفاده از couplant مناسب با دمای سطح ضروری است؛ couplant نامناسب در دمای بالا خشک می‌شود و کیفیت سیگنال افت می‌کند. در خطوط outdoor، محافظت کابل و transducer در برابر UV، باران و ضربه مکانیکی نیز باید دیده شود.</p><p>در مدل‌های inline، مزیت اصلی کنترل بهتر هندسه و امکان کالیبراسیون spool است، اما همچنان نصب پایپینگ، gasket، alignment و طول مستقیم اهمیت دارد. اگر فلومتر در نزدیکی control valve یا pump نصب شود، profile جریان می‌تواند خطا ایجاد کند. برای خطوط بزرگ یا کاربردهای دقیق‌تر، multi-path ultrasonic ممکن است عملکرد بهتری داشته باشد. در مایعات دارای ذرات، باید بررسی شود آیا Doppler واقعاً سیگنال بازتاب کافی دریافت می‌کند یا خیر.</p><h2>مقایسه با سایر فناوری‌ها</h2><p>فلومتر التراسونیک همیشه جایگزین magnetic، vortex یا Coriolis نیست. اگر سیال رسانا و خط قابل برش است، magmeter ممکن است دقت و پایداری بهتری بدهد. اگر جرم دقیق یا چگالی لازم است، Coriolis مناسب‌تر است. اگر بخار یا گاز با شرایط مشخص دارید، vortex یا DP flow ممکن است گزینه عملی‌تری باشد. مزیت اصلی ultrasonic در نصب بدون افت فشار، امکان clamp-on و کاربرد در سایزهای بزرگ است. بنابراین انتخاب باید بر اساس هدف اندازه‌گیری و محدودیت نصب انجام شود.</p><h2>مدیریت داده و نگهداری</h2><p>اگر فلومتر برای energy monitoring یا water balance استفاده می‌شود، خروجی آن باید با سیستم ثبت داده هماهنگ شود. scaling در PLC/DCS، واحد دبی، totalizer، alarm و trend باید در commissioning کنترل شود. اگر از فلومتر portable برای ممیزی استفاده می‌شود، محل نصب، مدت اندازه‌گیری، کیفیت سیگنال و شرایط فرایند باید در گزارش ثبت شود تا نتایج قابل مقایسه باشند.</p><ul><li>Signal strength و signal quality باید هنگام نصب ثبت شود.</li><li>اطلاعات واقعی لوله باید از اندازه‌گیری یا مدارک معتبر گرفته شود.</li><li>در خطوط دو فازی، خطای measurement باید جداگانه بررسی شود.</li><li>برای کاربردهای billing، روش کالیبراسیون و uncertainty باید شفاف باشد.</li></ul><p>در نهایت، پذیرش فلومتر التراسونیک باید بر اساس شرایط واقعی سایت انجام شود، نه فقط عدد دقت کاتالوگ. اگر هدف پایش روند است، repeatability و پایداری مهم‌تر از دقت مطلق است. اگر هدف محاسبه مصرف یا گزارش رسمی است، calibration و traceability اهمیت بیشتری دارد.</p></section>''',
'services/products/deaerator-feedwater-system.html': '''<section class="ptf-box" data-mixed-phase2-depth="deaerator"><h2>تکمیل کنترل کیفیت و راه‌اندازی دی‌اریاتور</h2><p>در دی‌اریاتور، کنترل عملکرد فقط با مشاهده سطح مخزن انجام نمی‌شود. دمای آب خروجی باید با فشار کاری و نقطه اشباع مقایسه شود، vent باید به‌درستی تنظیم باشد و oxygen residual باید در محدوده مورد قبول برنامه شیمی آب قرار گیرد. اگر اکسیژن بالا باقی بماند، ممکن است spray nozzle، tray، vent، فشار بخار، دمای آب ورودی یا ورود هوا از مسیر کندانس مشکل داشته باشد. برای همین در commissioning باید هم ابزار دقیق و هم پارامترهای شیمیایی بررسی شوند.</p><p>Feedwater pumpها باید با شرایط آب داغ کار کنند. کنترل NPSH، ارتفاع نصب، افت مکش، دمای آب و عملکرد minimum flow بسیار مهم است. اگر پمپ در دبی پایین کار کند، گرمایش داخلی و آسیب seal ممکن است رخ دهد. اگر سطح دی‌اریاتور نوسان دارد، پمپ ممکن است هوا بکشد و لرزش یا کاویتاسیون ایجاد شود. در پکیج‌های مهم، وجود پمپ standby و تست دوره‌ای آن باید در برنامه بهره‌برداری باشد.</p><h2>مدارک ساخت و تحویل پکیج</h2><p>برای vessel، مدارک welding، NDT، hydrotest، MTC، pressure relief، painting و nameplate اهمیت دارد. برای پمپ‌ها، curve، test report، motor datasheet، seal، coupling و alignment procedure باید تحویل شود. برای instrumentها، datasheet، calibration و loop diagram لازم است. اگر control valve بخار یا make-up water در پکیج وجود دارد، Cv، actuator، fail position و setting باید بررسی شود.</p><ul><li>قبل از راه‌اندازی، مسیر vent، overflow، drain و safety valve بازبینی شود.</li><li>در بهره‌برداری، oxygen، دما، فشار، سطح و آمپر پمپ پایش شود.</li><li>مواد شیمیایی scavenger نباید جایگزین عملکرد مکانیکی دی‌اریاتور شود.</li><li>Data Book باید vessel، pump، instrument و valve را به صورت یک پکیج پوشش دهد.</li></ul><p>اگر دی‌اریاتور برای توسعه ظرفیت بویلر خریداری می‌شود، باید با load جدید، درصد کندانس برگشتی و کیفیت آب آینده هماهنگ باشد. در غیر این صورت، تجهیز جدید ممکن است در روز اول کافی به نظر برسد اما در ظرفیت واقعی کارخانه محدودیت ایجاد کند.</p></section>'''
}

for rel, extra in EXTRAS.items():
    p=Path(rel)
    html=remove_dup(p.read_text(encoding='utf-8'))
    marker=extra.split('data-mixed-phase2-depth="',1)[1].split('"',1)[0]
    if f'data-mixed-phase2-depth="{marker}"' not in html:
        html=html.replace('</article>', extra+'</article>', 1)
    p.write_text(html, encoding='utf-8')
    print('extended', rel)
