/* =====================================================================
   PTF CRM — راهنمای درون‌برنامه‌ای
   منبع راهنمای کاربران. هر قابلیت عملیاتی جدید باید هم‌زمان یک entry در GUIDE
   و سند نگهداشت docs/CRM-USER-GUIDE-MAINTENANCE-FA.md دریافت کند.
   ===================================================================== */
(function () {
  'use strict';
  if (window.__ptfUserGuideLoaded) return;
  window.__ptfUserGuideLoaded = true;

  function esc(v) { return String(v == null ? '' : v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
  function role() { try { return String(curRole() || 'sales'); } catch (e) { return 'sales'; } }
  function canSee(entry) { return !entry.roles || entry.roles.indexOf(role()) > -1; }
  function text(entry) { return [entry.title, entry.group, entry.purpose, entry.when, entry.result, entry.warning, (entry.steps || []).join(' ')].join(' ').toLowerCase(); }

  /* هر entry یک قرارداد محصولی است: هدف، مسیر، مراحل، خروجی و مرز خطا. */
  var GUIDE = [
    { group:'شروع کار', title:'داشبورد و روز من', purpose:'نمای کلی کارهای امروز، شاخص‌های فروش و میان‌بر ماژول‌ها.', when:'ابتدای هر روز کاری', steps:['کارت‌های «روز من» را بررسی کنید.','روی مورد اقدام‌دار کلیک کنید تا به بخش مربوط بروید.','کاشی‌های داشبورد را مطابق اولویت خود جابه‌جا کنید.'], result:'کارهای فوری و شاخص‌های مهم در یک صفحه دیده می‌شوند.', warning:'کارت روز من یک یادآور است؛ انجام واقعی کار باید در ماژول مقصد ثبت شود.' },
    { group:'شروع کار', title:'کارتابل و اعلانات', purpose:'فقط کارهای نیازمند اقدام شما مانند ارجاع، یادآور، چک و درخواست امضا.', when:'پس از ورود و هنگام دریافت اعلان', steps:['بخش «اقدام لازم» را باز کنید.','«خواندم» فقط اعلان را برای شما خوانده‌شده می‌کند.','برای انجام واقعی کار دکمه «برو» را بزنید و عملیات مبنا را کامل کنید.'], result:'ارجاع فقط پس از انجام رویداد مربوطه از کارتابل حذف می‌شود.', warning:'رفتن به یک بخش به‌تنهایی به معنی انجام ارجاع نیست.' },
    { group:'فروش', title:'سرنخ‌ها', purpose:'ثبت و پیگیری فرصت‌های اولیه پیش از تبدیل به مشتری یا درخواست.', roles:['admin','chairman','ceo','commercial','sales'], steps:['سرنخ جدید را با شرکت، شخص تماس و نیاز ثبت کنید.','پیگیری‌ها و نتیجه تماس را در تاریخچه ثبت کنید.','پس از قطعی‌شدن فرصت، مشتری یا درخواست ایجاد کنید.'], result:'تاریخچه پیگیری و وضعیت سرنخ قابل گزارش می‌شود.', warning:'ثبت مشتری تکراری را قبل از تبدیل بررسی کنید.' },
    { group:'فروش', title:'مشتریان و مالک پورسانت', purpose:'پرونده شرکت/شخص، رابط‌ها، سقف اعتبار، وضعیت AVL و مسئول فروش.', roles:['admin','chairman','ceo','commercial','sales'], steps:['مشتری را از بخش مشتریان ثبت یا ویرایش کنید.','رابط‌ها، تلفن‌ها و نام انگلیسی را تکمیل کنید.','مدیر ارشد در فیلد «کارشناس مسئول / مالک پورسانت» کاربر مسئول را انتخاب می‌کند.'], result:'پیشنهادها، وصولی‌ها و پورسانت به مشتری صحیح متصل می‌شوند.', warning:'تغییر مالک مشتری روی محاسبه پورسانت دوره‌های آینده اثر دارد و audit می‌شود.' },
    { group:'فروش', title:'درخواست مشتری (RFQ)', purpose:'ثبت نیاز مشتری، موعد پاسخ، شرح و پیوست‌های درخواست.', roles:['admin','chairman','ceo','commercial','sales'], steps:['مشتری و موضوع را انتخاب کنید.','موعد پاسخ و شرح/پیوست را وارد کنید.','اقلام را در همان فرم یا ویرایش اقلام وارد کنید.','پیوست جدید، جایگزینی یا حذف را تا دریافت پیام «روی سرور ثبت و تأیید شد» دنبال کنید.'], result:'یک کد RFQ و نقطه شروع فرآیند فروش ایجاد می‌شود.', warning:'اگر ACK سرور نیامد، پیام دقیق خطا را رفع و دوباره تلاش کنید؛ سیستم فایل uploadشده بدون metadata را پاک‌سازی می‌کند.' },
    { group:'فروش', title:'اقلام درخواست', purpose:'تعریف کالا، تعداد، واحد و مشخصات فنی هر درخواست.', roles:['admin','chairman','ceo','commercial','sales','buyer'], steps:['از درخواست، «ویرایش اقلام» را باز کنید.','قلم را دستی، اکسل یا دستیار وارد کنید.','مشخصات/استاندارد را کامل کنید.'], result:'اقلام در پیشنهاد فنی/مالی و خرید واقعی قابل استفاده‌اند.', warning:'اقلام بدون شرح یا مشخصه کافی، کیفیت پیشنهاد و تأمین‌کننده را پایین می‌آورند.' },
    { group:'فروش', title:'پیشنهاد فنی و مالی (TO/CO)', purpose:'ساخت پیشنهاد فنی یا مالی از اقلام درخواست.', roles:['admin','chairman','ceo','commercial','sales'], steps:['نوع پیشنهاد را انتخاب و مشتری/درخواست را متصل کنید.','اقلام را از درخواست بارگذاری یا ویرایش کنید.','برای CO قیمت، ارز، اعتبار و شرایط را تکمیل کنید.','ذخیره را بزنید و رسید «تأیید سرور» را ببینید.'], result:'پیشنهاد با شماره رسمی و نگارش قابل چاپ ایجاد می‌شود.', warning:'پیشنهاد برنده از این بخش قابل ویرایش نیست؛ ادامه کار فقط از پرونده فروش است.' },
    { group:'فروش', title:'پرونده فروش و پس از برد', purpose:'مدیریت اجرای پیشنهاد برنده از خرید واقعی تا دریافت، تحویل، کنترل کیفیت و مختومه‌سازی.', roles:['admin','chairman','ceo','commercial','sales'], steps:['آخرین Revision پیشنهاد را برنده کنید؛ برد و پرونده یکتا با تأیید سرور هم‌زمان ثبت می‌شوند.','کادر «کار لازم برای مرحله بعد» را انجام دهید و خرید واقعی، QC، پکینگ، بارنامه و تحویل را در پرونده ثبت کنید.','برای مدرک اشتباه از اصلاح، جایگزینی نسخه یا حذف با دلیل استفاده کنید؛ مرحله خودکار از شواهد باقی‌مانده بازمحاسبه می‌شود.','دریافت قطعی را فقط از «دریافت و حساب پرونده» ثبت کنید.'], result:'پرونده یکتا با مرحله مبتنی بر شاهد، بستانکاری، مطالبات و اسناد قابل حسابرسی پیگیری می‌شود.', warning:'وجود شاهد تکمیل‌شده بعدی مانع عقب‌گرد مرحله است؛ شرایط پرداخت یا paid روی پیشنهاد نیز پول واقعی نیست.' },
    { group:'تأمین', title:'تأمین‌کنندگان و تخصص', purpose:'ثبت تأمین‌کننده، برند/تجهیزات تخصصی، تماس‌ها و کیفیت همکاری.', roles:['admin','chairman','ceo','commercial','buyer','sales'], steps:['تأمین‌کننده را ثبت و تخصص برند/تجهیزات را تکمیل کنید.','درخواست تأمین را از RFQ یا پرونده بسازید.','پاسخ و قیمت‌ها را ثبت و مقایسه کنید.'], result:'پیشنهاد تأمین‌کننده و امتیازدهی بر اساس تخصص دقیق‌تر می‌شود.', warning:'نام تأمین‌کننده را با رکورد موجود تطبیق دهید تا تکراری ایجاد نشود.' },
    { group:'تأمین', title:'خرید واقعی و مقایسه قیمت', purpose:'ثبت قیمت واقعی، تأمین‌کننده نهایی، ارز، پرداخت و سابقه خرید.', roles:['admin','chairman','ceo','commercial','buyer'], steps:['برای قلم، تأمین‌کننده یکتای ثبت‌شده و قیمت واحد را انتخاب کنید.','خرید نهایی و در خرید ارزی نرخ تسعیر را ثبت کنید.','خرید نقدی خودکار به‌صورت سند خرید + پرداخت کامل در گردش همان تأمین‌کننده می‌نشیند و مانده صفر می‌شود.'], result:'هزینه واقعی پروژه و تاریخچه خرید تأمین‌کننده حتی با حساب بسته حفظ می‌شود.', warning:'نام دستی مبهم برای خرید نقدی پذیرفته نمی‌شود؛ ابتدا تأمین‌کننده را یکتا ثبت/اصلاح کنید.' },
    { group:'تأمین', title:'فاکتور و پرداخت تأمین‌کننده', purpose:'زیر‌دفتر خرید، بدهی، اعتبار، پرداخت و اسناد تأمین‌کنندگان.', roles:['admin','chairman','ceo','commercial','accountant','buyer'], steps:['فاکتور خرید را با تاریخ، ارز، نرخ و پیوست ثبت کنید.','پرداخت را به فاکتورهای باز تخصیص دهید؛ خرید نقدی واقعی این دو ردیف را خودکار و کاملاً تخصیص‌یافته می‌سازد.','گردش حساب تأمین‌کننده صفر را نیز برای مشاهده سابقه خرید باز کنید.'], result:'مانده و تمام خریدها/پرداخت‌های تأمین‌کننده، حتی پس از تسویه کامل، قابل تطبیق است.', warning:'فاکتور پوششی با خرید واقعی متفاوت است؛ نوع سند و نرخ ارز را دقیق ثبت کنید.' },
    { group:'مالی', title:'فاکتور رسمی، دریافت و مطالبات', purpose:'ثبت فاکتور صادرشده در حسابداری/مودیان، دریافت قطعی پرونده، تخصیص FIFO و پیگیری مانده مشتری.', roles:['admin','chairman','ceo','commercial','accountant'], steps:['فاکتور رسمی خارجی را با شماره، شناسه مودیان، مبلغ پایه و درصد VAT ثبت کنید؛ مالیات/کل خودکار است.','حداقل تصویر/PDF فاکتور حسابداری یا سند مودیان را پیوست و هشدار OCR را بررسی کنید.','دریافت را از پرونده ثبت کنید؛ پیش‌دریافت به پایه و دریافت بعدی ابتدا به پایه سپس VAT تخصیص می‌یابد.'], result:'بستانکاری پرونده، مطالبات باز و خزانه از رویداد واحد و قابل اصلاح ساخته می‌شوند.', warning:'ابطال فاکتور مطالبات را حذف و تخصیص را به بستانکاری برمی‌گرداند، ولی پول واقعی خزانه باقی می‌ماند.' },
    { group:'مالی', title:'تنخواه و هزینه مستقیم', purpose:'ثبت هزینه‌های تنخواه، شارژ، تسویه، پرداخت مستقیم و گزارش دوره.', roles:['admin','chairman','ceo','commercial','sales','buyer','accountant','collector'], steps:['هزینه را با مبلغ، دسته، شرح و مدرک ثبت کنید.','تنخواه‌گردان شارژ یا تسویه را ثبت می‌کند.','در پایان دوره گزارش و صورتحساب بانک را به حسابدار ارجاع دهید.'], result:'مانده تنخواه و هزینه‌های دوره قابل پیگیری است.', warning:'شارژ تنخواه خروج بانک است؛ تسویه/پرداخت از همان مانده نباید دوباره خروج بانک شمرده شود.' },
    { group:'مالی', title:'هزینه‌های جاری (OPEX)', purpose:'هزینه‌های مستقل شرکت، هزینه لینک‌شده به پرونده و اسناد آن.', roles:['admin','chairman','ceo','commercial','accountant'], steps:['دسته، ماه شمسی، مبلغ و شرح را ثبت کنید.','در صورت ارتباط با فروش، پرونده را لینک کنید.','نوع رسمی/غیررسمی و سند را تعیین کنید.'], result:'هزینه در سود سال مالی یا هزینه پرونده لحاظ می‌شود.', warning:'هزینه لینک‌شده نباید دوباره به صورت هزینه مستقل ثبت شود.' },
    { group:'مالی', title:'چک‌ها و دسته‌چک', purpose:'چک‌های صادره/وارده، ضمانت، انتقال، سررسید و اسناد.', roles:['admin','chairman','ceo','commercial','accountant','collector'], steps:['نوع چک و مالکیت را درست انتخاب کنید.','برای چک شرکتی بانک/حساب/طرف و سررسید را کامل کنید.','وصول، پاس، انتقال، استرداد یا ابطال را از همان رکورد ثبت کنید.'], result:'یادآورها، بدهی/وصول و خزانه بر اساس وضعیت واقعی چک به‌روز می‌شوند.', warning:'نام روی دسته‌چک با مالکیت مالی چک یکی نیست.' },
    { group:'مالی', title:'خزانه و بانک', purpose:'نمای مشتق از ورود و خروج نقد واقعی؛ جایگزین صورتحساب بانک یا حساب بانکی مستقل نیست.', roles:['admin','chairman','ceo','commercial'], steps:['خروجی‌های خزانه و منبع هر ردیف را بررسی کنید.','شارژ تنخواه را خروج بانک بدانید.','پرداخت پورسانت بانکی و چک سررسیدشده را بررسی کنید.'], result:'تصویر عملیاتی نقدینگی و کسری قابل مشاهده است.', warning:'هزینه از مانده تنخواه خروج بانک دوم نیست.' },
    { group:'مالی', title:'پورسانت فروش', purpose:'محاسبه، تصویب دوره، ایجاد بدهی و پرداخت بانکی پورسانت.', roles:['admin','chairman','ceo','commercial'], steps:['دوره شمسی و مبنای محاسبه را انتخاب کنید.','مالک‌ندارها را در مشتریان اصلاح کنید.','دوره را تصویب کنید تا هزینه غیررسمی و بدهی ایجاد شود.','پرداخت بانکی را با شماره سند ثبت کنید.'], result:'هزینه در زمان تصویب و خروج بانک در زمان پرداخت ثبت می‌شود.', warning:'درصدها فقط در تنظیمات تعیین می‌شوند؛ پرداخت دوباره هزینه جدید ایجاد نمی‌کند.' },
    { group:'مالی', title:'سهامداران، حقوق و فراخوان نقدینگی', purpose:'سهام، حقوق موظف، علی‌الحساب، طلب/بدهی صندوق و تقسیم سود.', roles:['admin','chairman','ceo','commercial'], steps:['سهامدار و درصد/حقوق را ثبت کنید.','حقوق ماه را ایجاد و پرداخت را با سند ثبت کنید.','فراخوان نقدینگی و پرداخت هر سهم را پیگیری کنید.'], result:'مانده هر سهامدار و بدهی/طلب صندوق قابل مشاهده است.', warning:'حقوق، علی‌الحساب سود نیست و در گزارش تقسیم سود رفتار جدا دارد.' },
    { group:'مالی', title:'سال مالی، تراز و کیفیت داده', purpose:'گزارش سود، قفل سال، سند اصلاحی، تراز رسمی/غیررسمی و خطاهای داده.', roles:['admin','chairman','ceo','commercial','accountant'], steps:['سال و داده‌های ناقص را بررسی کنید.','قبل از قفل، سود، هزینه و وصولی‌ها را تطبیق دهید.','بعد از قفل فقط سند اصلاحی ایجاد کنید.'], result:'گزارش‌های مدیریتی و ممیزی‌پذیر دوره تولید می‌شوند.', warning:'قفل سال برگشت‌پذیر عادی نیست؛ اعداد و اسناد را پیش از قفل بررسی کنید.' },
    { group:'اسناد و ارتباطات', title:'نامه‌ها، قراردادها و اسناد رسمی', purpose:'مکاتبات، امضا، قرارداد، نوت بازرسی و پکینگ‌لیست.', roles:['admin','chairman','ceo','commercial','sales','buyer'], steps:['سند را به مشتری/پرونده صحیح متصل کنید.','فایل و نسخه را ثبت کنید.','برای سند نیازمند امضا، امضاکننده را تعیین و وضعیت را پیگیری کنید.'], result:'سند قابل جستجو و همراه پرونده باقی می‌ماند.', warning:'آپلود فایل کافی نیست؛ برای اتصال قطعی به رکورد، فرم را ذخیره کنید.' },
    { group:'اسناد و ارتباطات', title:'پیامک، پیام‌رسان و قالب پیام', purpose:'ارسال پیام‌های سازمانی و ارتباط سریع با مشتری/تأمین‌کننده.', roles:['admin','chairman','ceo','commercial','sales','buyer'], steps:['شماره را بررسی کنید.','قالب مناسب را انتخاب و پیش‌نمایش کنید.','ارسال و وضعیت صف را پیگیری کنید.'], result:'ارتباط قابل ردگیری و هم‌راستا با رکورد مشتری انجام می‌شود.', warning:'ارسال پیامک به معنی تأیید انجام فرآیند فروش یا مالی نیست.' },
    { group:'ابزارهای هوشمند', title:'دستیار AI و خواندن فایل', purpose:'استخراج اقلام، کارت ویزیت، ترجمه، خلاصه و پیشنهاد اولیه از فایل.', roles:['admin','chairman','ceo','commercial','sales','buyer','accountant','collector'], steps:['فایل یا متن را وارد کنید.','خروجی AI را قبل از ثبت بازبینی کنید.','فقط پس از تأیید، مشتری/درخواست/اقلام را ایجاد کنید.'], result:'ورود داده سریع‌تر می‌شود.', warning:'خروجی AI پیشنهادی است؛ مشخصات فنی، مبلغ و طرف معامله را انسانی کنترل کنید.' },
    { group:'مدیریت', title:'گزارش‌ها، تحلیلگر و تصمیم‌یار', purpose:'گزارش روند فروش، تحلیل مشتری، KPI و اقدام مدیریتی.', roles:['admin','chairman','ceo','commercial'], steps:['بازه و فیلتر را انتخاب کنید.','منبع عدد و داده ناقص را بررسی کنید.','اقدام مدیریتی را به مسئول و موعد ارجاع دهید.'], result:'تصمیم‌ها به اقدام قابل پیگیری تبدیل می‌شوند.', warning:'گزارش مدیریتی جای اسناد حسابداری یا تراز بانکی رسمی نیست.' },
    { group:'مدیریت', title:'مدیریت کاربران و دسترسی‌ها', purpose:'ساخت کاربر، نقش، دسترسی اختصاصی و کنترل امنیت.', roles:['admin','chairman','ceo','commercial'], steps:['کاربر و نقش پایه را تعریف کنید.','در صورت نیاز، دسترسی ماژول‌ها را شخصی‌سازی کنید.','مالک مشتری و درصد پورسانت را جداگانه تنظیم کنید.'], result:'هر شخص فقط بخش‌های مجاز را می‌بیند.', warning:'نقش و دسترسی را قبل از واگذاری حساب کنترل کنید.' },
    { group:'تنظیمات و ایمنی', title:'ذخیره، Sync، بک‌آپ و بازیابی', purpose:'وضعیت تأیید سرور، ظرفیت دستگاه، پشتیبان و بازگردانی.', steps:['پس از هر ثبت مهم، رسید تأیید سرور/نشان سبز را بررسی کنید.','هشدار زرد یا قرمز را قبل از بستن تب حل کنید.','بک‌آپ دوره‌ای و فایل خارج از سامانه را نگه دارید.','بازیابی را فقط با بررسی اثر آن انجام دهید.'], result:'ریسک از دست‌رفتن داده و خطای مرورگر کاهش می‌یابد.', warning:'پاک‌سازی کامل کش، restore و Go-live عملیات حساس هستند و نباید آزمایشی اجرا شوند.' }
  ];

  function guideCss() {
    if (document.getElementById('ptfGuideCss')) return;
    var s = document.createElement('style'); s.id = 'ptfGuideCss';
    s.textContent = '#ptfUserGuide{margin-top:14px;padding:14px;border:1px solid var(--brd);border-radius:16px;background:var(--crd,#fff)}#ptfUserGuide .ug-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}#ptfUserGuide .ug-search{min-width:220px;max-width:360px;flex:1;padding:9px 11px;border:1px solid var(--brd);border-radius:10px;background:var(--crd,#fff);color:var(--tx)}#ptfUserGuide .ug-nav{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}#ptfUserGuide .ug-nav button{font-size:11.5px;padding:5px 9px}#ptfUserGuide .ug-card{border:1px solid var(--brd);border-radius:12px;margin:8px 0;background:var(--crd,#fff)}#ptfUserGuide .ug-card summary{cursor:pointer;padding:11px 12px;display:flex;justify-content:space-between;gap:8px;list-style:none}#ptfUserGuide .ug-card summary::-webkit-details-marker{display:none}#ptfUserGuide .ug-card summary small{color:#64748b;font-size:11px}#ptfUserGuide .ug-body{padding:0 14px 13px;line-height:1.9;font-size:12.5px;color:var(--tx,#334155)}#ptfUserGuide .ug-body h5{margin:9px 0 3px;color:var(--pri,#0e7490);font-size:12.5px}#ptfUserGuide .ug-body ol{margin:4px 0;padding-right:20px}#ptfUserGuide .ug-note{background:#fff7ed;border:1px solid #fed7aa;border-radius:9px;padding:7px 9px;color:#92400e;margin-top:8px;font-size:11.5px}#ptfUserGuide .ug-empty{padding:18px;text-align:center;color:#64748b}@media(max-width:600px){#ptfUserGuide .ug-search{max-width:none;width:100%}}';
    document.head.appendChild(s);
  }
  function groups() { var m = {}; GUIDE.forEach(function (x) { if (canSee(x)) m[x.group] = 1; }); return Object.keys(m); }
  function entryHtml(x) { return '<details class="ug-card" data-guide="' + esc(text(x)) + '"><summary><span><b>' + esc(x.title) + '</b><br><small>' + esc(x.purpose) + '</small></span><small>' + esc(x.group) + '</small></summary><div class="ug-body"><h5>چه زمانی استفاده کنم؟</h5><div>' + esc(x.when || 'هنگام نیاز به این فرآیند') + '</div><h5>مراحل استفاده</h5><ol>' + (x.steps || []).map(function (s) { return '<li>' + esc(s) + '</li>'; }).join('') + '</ol><h5>خروجی مورد انتظار</h5><div>' + esc(x.result || '') + '</div>' + (x.warning ? '<div class="ug-note"><b>نکته مهم:</b> ' + esc(x.warning) + '</div>' : '') + '</div></details>'; }
  window.ptfGuideFilter = function () { var q = String((document.getElementById('ptfGuideSearch') || {}).value || '').trim().toLowerCase(), group = window._ptfGuideGroup || ''; document.querySelectorAll('#ptfUserGuide .ug-card').forEach(function (el) { var hit = !q || String(el.getAttribute('data-guide') || '').indexOf(q) > -1; var groupHit = !group || el.querySelector('summary small').textContent === group; el.style.display = hit && groupHit ? '' : 'none'; }); var count = Array.prototype.filter.call(document.querySelectorAll('#ptfUserGuide .ug-card'), function (x) { return x.style.display !== 'none'; }).length; var empty = document.getElementById('ptfGuideEmpty'); if (empty) empty.style.display = count ? 'none' : ''; };
  window.ptfGuideGroup = function (g) { window._ptfGuideGroup = g || ''; var old = document.getElementById('ptfUserGuide'); if (old) old.outerHTML = window.ptfUserGuideHtml(); };
  window.ptfUserGuideHtml = function () {
    guideCss(); var gs = groups();
    return '<section id="ptfUserGuide" data-settings-title="راهنمای کامل استفاده از CRM"><div class="ug-head"><div><h4 style="margin:0">📚 راهنمای کامل استفاده از نرم‌افزار</h4><small style="color:#64748b">راهنمای مرحله‌به‌مرحله هر بخش، نقش، خروجی و نکته ایمنی. برای یافتن سریع، جستجو کنید.</small></div><input id="ptfGuideSearch" class="ug-search" oninput="ptfGuideFilter()" placeholder="جستجو: مشتری، فاکتور، چک، تنخواه، پیشنهاد…"></div><div class="ug-nav"><button class="bt bt-o" onclick="ptfGuideGroup(\'\')">همه بخش‌ها</button>' + gs.map(function (g) { return '<button class="bt bt-o" onclick="ptfGuideGroup(\'' + esc(g) + '\')">' + esc(g) + '</button>'; }).join('') + '</div><div id="ptfGuideList">' + GUIDE.filter(canSee).map(entryHtml).join('') + '<div id="ptfGuideEmpty" class="ug-empty" style="display:none">راهنمایی مطابق عبارت جستجو پیدا نشد.</div></div><div class="ug-note" style="background:#eff6ff;border-color:#bfdbfe;color:#1e3a8a"><b>قرارداد نگهداشت:</b> هر تغییر عملیاتی جدید باید هم‌زمان این راهنما و سند نگهداشت راهنما را به‌روز کند. راهنما بخشی از تعریف تکمیل قابلیت است.</div></section>';
  };
  function hookSettings() {
    if (window._ptfGuideSettingsHooked || typeof window.buildSettings !== 'function') return false;
    window._ptfGuideSettingsHooked = true;
    var old = window.buildSettings;
    window.buildSettings = function () { return old() + window.ptfUserGuideHtml(); };
    return true;
  }
  var tries = 0, timer = setInterval(function () { tries++; if (hookSettings() || tries > 60) clearInterval(timer); }, 250);
  hookSettings();
})();
